name: 'Trigger DBT Cloud Job'
description: 'Triggers a DBT cloud job specified by the job id.'
inputs:
  dbt_cloud_token:  # token for dbt cloud api
    description: 'DBT cloud api token'
    required: true
  dbt_cloud_account_id:  # account id
    description: 'DBT cloud account id'
    required: true
  dbt_cloud_job_id:  # job id
    description: 'DBT cloud job id'
    required: true
  cause:  # cause
    description: 'Cause message to use'
    required: true
    default: 'Triggered from Github'
runs:
  using: 'node12'
  main: 'index.js'